.github/workflows/pull_request.yaml

-   [ ] Feature
-   [x] Bug Fix
Workflow `pull_request.yml` virkede ikke korrekt. Detter nu blevet fikset. Se `File changed`.
Derudover er blevet tilføjet et build step for at afgøre, om applikationen overhovedet kan buildes.
-   Closes #
-   [x] No, and this is why: Fixed github workflow

Fixed pull request workflow

---

backend/api/Abstractions/IPageRepository.cs
backend/api/Controllers/PageController.cs
backend/api/Models/DTOs/PageResponseDto.cs
backend/api/Profiles/PageProfile.cs
backend/api/Program.cs
backend/api/Repositories/PageRepository.cs
backend/api/api.csproj

-   [x] Feature
Kan søge på /api/search med two query strings (q og language), som returnerer liste af artikler som indeholder værdien fra q. 
Eksempel: /api/search?q=javascript&language=en
-   Closes #
-   [x] No, and this is why: Kunne ikke få lortet til at virke, halp pls 😫

Feature/issue 11/api search endpoint

---

backend/api/Controllers/PageController.cs
backend/api/Program.cs
backend/api/api.csproj
backend/tests/PageTests.cs
backend/tests/TestDatabaseFactory.cs
backend/tests/tests.csproj

-   [x] Feature
Created Integration tests for `/api/search` endpoint for fetching Pages.
-   Closes #20 
-   [x] Yes, added
-   [ ] No, and this is why: _please replace this line with details on why tests

Page Integration Tests

---

backend/api/.env_sample
backend/api/Abstractions/IJwtGenerator.cs
backend/api/Controllers/PageController.cs
backend/api/Controllers/UserController.cs
backend/api/Models/DTOs/TokenUserResponseDto.cs
backend/api/Program.cs
backend/api/Services/JwtGenerator.cs
backend/api/api.csproj
backend/api/appsettings.json
backend/tests/PageTests.cs
backend/tests/TestDatabaseFactory.cs
backend/tests/UserTests.cs
backend/tests/tests.csproj

-   [x] Feature
Når du rammer `/api/login` og er godkendt på username/password, skabes en Jwt token via `JwtGenerator `klassen. Token sendes tilbage som response sammen med user info. JWT_KEY er blevet tilføjet til .env - det skal bare være en lang random string til at generere tokens.
-   Closes #19 
-   [x] Yes, updated
-   [ ] No, and this is why: Testede manuelt

Feature/issue 19/backend jwt

---

.github/workflows/tag_release.yaml
frontend/src/auth/AuthProvidor.tsx
frontend/src/services/UsersEndpoint.ts

-   [x] Refactor
-   [x] Feature
Token is now stored in localstorage and used to set the user to be logged in, even when browser is closed or refreshed.
-   Closes #
-   [x] No, and this is why: Frontend

feat: implemented token in frontend

---

backend/api/Program.cs

-   [ ] Feature
-   Closes #
-   [ ] No, and this is why: _please replace this line with details on why tests

fix: allow all cors

---

backend/api/Program.cs

-   [x] Refactor
-   [ ] Feature
Swagger is now enabled in prod
-   Closes #35 
-   [ ] No, and this is why: _please replace this line with details on why tests

feat: enabled swagger for prod

---

.github/issue_template.md

Har lavet et simpelt issue template
- Closes #39

feat: created basic issue_template.md

---

backend/api/Program.cs
backend/api/api.csproj
backend/api/appsettings.json
backend/tests/tests.csproj

Set up Serilog as default logger, makes logging look a bit nicer.
- Closes #

feat: Added Serilog for better logging experience

---

.github/workflows/tag_release.yaml

Added automated Postman API tests to deployment pipeline. Runs after deployment is finished.
- Closes #

feat: added automated api tests in pipeline

---

README.md

feat: added badges

---

.github/workflows/mega_linter.yaml
.github/workflows/pull_request.yaml
.github/workflows/tag_release.yaml
backend/api/Controllers/WeatherController.cs

fix: updated workflows; set /api/weather caching to 1 hour

---

.github/workflows/tag_release.yaml
frontend/Dockerfile

Changed VM to digitalocean droplet.
User: root
IP: 67.207.73.30 (Reserved, fixed IP)
Same SSH key as before.
- Closes #

feat: updated to using droplet VM

---

.github/workflows/tag_release.yaml

fix: fixed workflow env drilling

---

frontend/src/pages/RegisterPage.tsx

Når bruger registrerer sig, så bliver han logget ind og bliver redirected til search page. 
- Closes #75

feat: now logs in user after registering

---

.github/workflows/tag_release.yaml
docker-compose.yml

scp docker-compose to VM

---

.github/workflows/tag_release.yaml

feat: now scp nginx conf file to VM

---

frontend/Dockerfile

fix: removed specified port in frontend Dockerfile

---

docker-compose.yml
nginx.conf

Setting up HTTPS and domain routing
- Closes #

feat: setup https and domain

---

.github/workflows/tag_release.yaml

fix: changed API_URL back to IP

---

.github/workflows/tag_release.yaml

fix: added correct api url

---

.github/workflows/tag_release.yaml
docker-compose.yml
nginx.conf

Added docker scout when tag releasing
- Closes #

feat: added docker scout; added secrets in tag_release

---

frontend/Dockerfile

feat: updated node version in frontend Dockerfile

---

backend/api/Controllers/UserController.cs
backend/api/Models/DTOs/UserResponseDto.cs
backend/api/Services/JwtGenerator.cs
backend/tests/UserTests.cs
frontend/src/App.tsx
frontend/src/auth/AuthProvidor.tsx
frontend/src/components/layouts/Header.tsx
frontend/src/models/User.ts
frontend/src/pages/LoginPage.tsx
frontend/src/pages/RegisterPage.tsx
frontend/src/pages/ResetPasswordPage.tsx
frontend/src/pages/SearchPage.tsx
frontend/src/services/UsersEndpoint.ts

Der er blevet lavet en page, hvor bruger har mulighed for at ændre sit password. Når bruger trykker "submit", så bliver der kaldt et PATCH /users/${id} med body som beskrevet i issue #102. Derudover er der blevet tilføjet en nofikation om at ændre sit password, hvis man ikke allerede har gjort det.
I backenden returnerer register og login ID'et på brugeren i ResponseDTO. Det samme er gældende for JWT claims, hvor id er blevet tilføjet. Dette er blevet gjort, da endpointet PATCH /users/id skal bruge det.
- Related Issue #102 
- Closes #

Frontend - Change Password

---

backend/api/Migrations/20241108090408_page-indexes.Designer.cs
backend/api/Migrations/20241108090408_page-indexes.cs
backend/api/Models/Entities/Page.cs

feat: added indexes for page table

---

frontend/src/services/ApiClient.ts
frontend/src/services/UsersEndpoint.ts

fix: fixed change password endpoint in frontend

---

.github/workflows/deploy_monitoring.yaml

fix: changed folders in deploy_monitoring

---

.github/workflows/deploy_monitoring.yaml
monitoring/custom.ini
monitoring/docker-compose.yml
monitoring/prometheus.yml

Monitoring er nu oppe at køre på [monitoring.abdevops.dk](https://monitoring.abdevops.dk).
Credentials:
username: admin
password: nothing2hide
Der er blevet oprettet 3 dashboards deroppe.
- Closes #112

Fix monitoring

---

documents/sla.md
terraform/data.tf
terraform/monitoring.tf
terraform/production.tf
terraform/provider.tf
terraform/variables.tf

feat: Added SLA
